=== juanrm27/ASIGNATURAS/LM/Tema 3/unidad_04/Enunciado2XSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="biblioteca">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="libro" minOccurs="2" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="libro">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="autor" type="xs:string" maxOccurs="5"/>
        <xs:element name="editorial" type="tipo_editorial"/>
        <xs:element name="edicion" type="xs:string" minOccurs="0" maxOccurs="1"/>
        <xs:element name="isbn" type="tipo_isbn"/>
        <xs:element name="donacion" type="xs:string" minOccurs="0" maxOccurs="1"/>
        <xs:element name="ubicacion" type="tipoUbicacion"/>
        <xs:element ref="caracteristicas"/>
      </xs:sequence>
      <xs:attribute name="codigo" type="tipo_codigo" use="required"/>
      <xs:attribute name="titulo" type="xs:string" use="required"/>
      <xs:attribute name="fecha_publicacion" type="xs:date" use="required"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="caracteristicas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Numero_Paginas">
          <xs:simpleType>
            <xs:restriction base="xs:short">
              <xs:maxInclusive value="430"/>
              <xs:minInclusive value="160"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="encuadernación">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="Rústica"/>
              <xs:enumeration value="Bolsillo"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:simpleType name="tipo_isbn">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9][0-9]-[0-9][0-9]-[0-9][0-9][0-9][0-9]"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="tipo_codigo">
    <xs:restriction base="xs:ID">
      <xs:length value="3"/>
    </xs:restriction>
  </xs:simpleType>
 
  <xs:simpleType name="tipo_editorial">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Bloomsbury Publishing"/>
      <xs:enumeration value="Del Rey Books"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="tipoUbicacion">
    <xs:attribute name="sede" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="norte"/>
          <xs:enumeration value="sur"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
  
</xs:schema>

=== juanrm27/ASIGNATURAS/LM/Tema 3/unidad_04/Enunciado2XSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Enunciado2XSD.xsd">

  <libro codigo="A12" titulo="Harry Potter" fecha_publicacion="1997-06-30">
    <autor>J.K. Rowling</autor>
    <editorial>Bloomsbury Publishing</editorial>
    <edicion>3</edicion>
    <isbn>12-34-5678</isbn>
    <donacion/>
    <ubicacion sede="norte"/>
    <caracteristicas>
      <Numero_Paginas>240</Numero_Paginas>
      <encuadernación>Bolsillo</encuadernación>
    </caracteristicas>
  </libro>
  
  <libro codigo="B34" titulo="El laberinto del mal(Star Wars)" fecha_publicacion="1977-08-27">
    <autor>James Luceno</autor>
    <editorial>Del Rey Books</editorial>
    <isbn>12-11-2222</isbn>
    <ubicacion sede="sur"/>
    <caracteristicas>
      <Numero_Paginas>180</Numero_Paginas>
      <encuadernación>Rústica</encuadernación>
    </caracteristicas>
  </libro>
  
</biblioteca>
