=== juanrm27/ASIGNATURAS/LM/Tema 3/Ejercicios/ejercicio1.dtd
<!ELEMENT biblioteca (libro, libro)+>
    <!ELEMENT libro(titulo, autor, foto_portada, editorial, edicion, ISBN, ubicacion)
        <!ATTLIST libro codigo ID #REQUIRED
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT autor (#PCDATA)>
    <!ELEMENT foto_portada (#PCDATA)>
    <!ELEMENT editorial (#PCDATA)>
    <!ELEMENT edicion (#PCDATA)>
    <!ELEMENT ISBN (#PCDATA)>
    <!ELEMENT ubicacion (#PCDATA)>
        <!ATTLIST ubicacion sede (norte|sur|centro) #REQUIRED>

=== juanrm27/ASIGNATURAS/LM/Tema 3/Ejercicios/ejercicio1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE biblioteca SYSTEM "ejercicio1.dtd"> 
   
<biblioteca>
    <libro codigo="F16204">
        <titulo>Harry Potter y la piedra filosofal</titulo>
        <autor>J.K.Rowling</autor>
        <foto_portada imagen = "harrypotter.jpg"/>
        <editorial>Salamandra</editorial>
        <edicion>1999</edicion>
        <ISBN>978-84-7888-445-2</ISBN>
        <ubicacion sede="sur"/>
    </libro>
    <libro codigo="N67301">
        <titulo>Geronimo Stilton en el Reino de la Fantas√≠a</titulo>
        <autor>Geronimo Stilton</autor>
        <foto imagen="geronimo.jpg"/>
        <editorial>PLANETA</editorial>
        <edicion>2005</edicion>
        <ISBN>978-84-0806-099-4</ISBN>
        <ubicacion sede="centro"/>
    </libro>
</biblioteca>
